### ISSUE TITLE
Live demo

### ISSUE THREAD

**Issue by GarfieldsPipe** [ithrts/ImoutoIB#45] opened 2021-09-20 20:54 UTC
Is there a live demo site to visit?

**Comment by saintly2k** [comment] 2021-09-30 18:14
as soon as someone can resolve my error which i opened in a new ticket, at https://imouto.h33t.moe

**Comment by GarfieldsPipe** [comment] 2021-10-05 15:32
I managed to spin up a demo site myself but oh boy, is this software broken/unfinished.
The login session doesn't persist, so anything you click in the management panel you get logged out again. This for example makes it impossible to delete posts.
You have to create a lot of the board and upload folders manually and set permissions so posts can be made and images can be uploaded.
No way to disable the captcha.
Themes are broken.

Having said that, the software does look nice and definitely has potential so I hope it will be further developed.

**Comment by ithrts** [comment] 2021-10-05 16:54
> but oh boy, is this software broken/unfinished

Well, yeah it is pretty unfinished haha

>The login session doesn't persist, so anything you click in the management panel you get logged out again. This for example makes it impossible to delete posts.

Not the case for me. Do you have cookies enabled? Login session persists just fine, although currently if you log into another computer you will get logged out of the original login session. I think this is a good thing regarding moderator panels though.

>You have to create a lot of the board and upload folders manually and set permissions so posts can be made and images can be uploaded.

In my setup the code creates the folders with mkdir if they don't exist as it's coded to do. No permissions needed to be changed when I deployed it to server. You shouldn't need to create any folders. What did the permissions for all your files say when first uploaded? You should definitely not need to create any folders manually. Maybe I've forgotten to account for something with your particular setup, but that does not sound right at all.

>No way to disable the captcha.

Incorrect. You can set captcha to false in the default/custom config files in includes folder, and you can also enable/disable it on individual boards by going to the database/boards/board folder and setting a different setting in a config.php file you can create for different settings.

> Themes are broken.

Works completely fine here for me, imageboard/textboard uses different themes, as set by default or changed by user.
If you change one imageboard theme, it will change on all imageboards. If you change one textboard theme, it will change on all textboards.

>Having said that, the software does look nice and definitely has potential so I hope it will be further developed.

i personally think its pretty bad and people should use vichan or jschan, but thanks haha. I'll continue for a while whenever I feel like it. I want to at least make it usable enough to give a half decent user experience, and enough tools for admin/mod to do whatever they find necessary. After that maybe I'll create some things here and there, but will focus on a couple other projects most likely.


What's your setup you run it on? OS, PHP version, webhandler?
I'd love to see any error log that causes all of these issues if you have.
I'm running linux with PHP7.3 and apache for reference.

I'll try and copy the current github repo to a different server and see if everything works.

**Comment by ithrts** [comment] 2021-10-05 17:09
Okay so I've found some things from default configuration.

For cookies to work you need to go to custom.php and set your domain name otherwise your session wont save.

The frontpage does not load or work properly until you've created a single post on any board as this is what creates all the folders for the boards. I can probably find a fix for this.

I have no idea what you mean by themes not working though!

**Comment by GarfieldsPipe** [comment] 2021-10-06 15:23
OK so I wiped my server and started again. For the record: I'm using PHP 7.3 on Debian 10 using nginx as the web server.

First I git clone the repo to /var/www/html. Then I set write permissions (757) on /html/ (the root directory where all the files and folders are) and write permissions (757) on /database.

But when I open my.domain/main.php it gives these errors:

```
Warning: file_put_contents(/var/www/html/database/boards/img/counter.php): failed to open stream: No such file or directory in /var/www/html/main.php on line 16

Warning: file_get_contents(/var/www/html/database/boards/img/counter.php): failed to open stream: No such file or directory in /var/www/html/main.php on line 19

Warning: file_put_contents(/var/www/html/database/boards/txt/counter.php): failed to open stream: No such file or directory in /var/www/html/main.php on line 16

Warning: file_get_contents(/var/www/html/database/boards/txt/counter.php): failed to open stream: No such file or directory in /var/www/html/main.php on line 19
```

Which makes sense, because database/boards/img/counter.php doesn't exist, and neither do the others. If I *manually* create a folder in /database called 'boards', **presto** like magic the errors disappear and the files get created.

The same problem goes for the 'uploads' folder in the root directory. I also have to create that one manually before files from post can get placed into it.


Regarding the themes: they don't work. When I click Yotsuba B it goes to 'http://my.domain/?board=img&thread=&theme=Yotsuba%20B' but the theme doesn't change. Same goes for all the other themes.

**Comment by GarfieldsPipe** [comment] 2021-10-06 15:47
Also I see [only HTTPS](https://github.com/ithrts/ImoutoIB/blob/master/require.php#L62) is supported.
Could you add HTTP support too? I'm getting an "invalid cookie" error because I'm using an http domain.

**Comment by ithrts** [comment] 2021-10-06 22:35
>OK so I wiped my server and started again. For the record: I'm using PHP 7.3 on Debian 10 using nginx as the web server.

Good to know. I dont know why you need to create folders manually, I don't need to do this on my setup. I can try to troubleshoot it later, but I can't promise I find out what is wrong. I suspect it might have to do with nginx and permissions since it works just fine for me on apache.

>Weird thing: on Firefox browsers the theme links ( [Yotsuba B] [Yotsuba] [Burichan] [Futaba] [Cyanide] [Tomorrow] [Late] [Kind] [Kareha] [Sankarea) are hidden when you have JavaScript enabled like you intended, but on Chromium-related browsers those links are still visible together with the theme dropdown menu even when you have JavaScript enabled.

Working as intended. I've fixed this bug now, it was a broken html selector inside the noscript that webkit didnt fix, but firefox did fix it so i didnt notice. The links are supposed to show if you have javascript disabled so that you can set themes even without JS.
This should work now.

>PS: How do you ban a user?

That was not possible until just now, just uploaded a new commit for banning/warning posts. Still needs some minor work, but the actual warning/temp/permban is working as intended from what i can tell.

**Closed** 2021-10-12 00:38 UTC
Labels: fixed
